# -*- coding: utf-8 -*-
import unittest as ut

from nedda.staging.staging import tnm_stage

class Testtnm_stage(ut.TestCase):

    def test_prostate_cancer_I(self):
        self.assertEquals('I', tnm_stage('C61.9', 'T1a', 'N0', 'M0', '1', '6'))
        self.assertEquals('I', tnm_stage('C61.9', 'T1b', 'N0', 'M0', '1', '6'))
        self.assertEquals('I', tnm_stage('C61.9', 'T1c', 'N0', 'M0', '1', '6'))

        self.assertEquals('I', tnm_stage('C61.9', 'T2a', 'N0', 'M0', '1', '6'))

        self.assertEquals('I', tnm_stage('C61.9', 'T1', 'N0', 'M0', 'X', 'X'))
        self.assertEquals('I', tnm_stage('C61.9', 'T1a', 'N0', 'M0', 'X', 'X'))
        self.assertEquals('I', tnm_stage('C61.9', 'T1b', 'N0', 'M0', 'X', 'X'))
        self.assertEquals('I', tnm_stage('C61.9', 'T1c', 'N0', 'M0', 'X', 'X'))
        self.assertEquals('I', tnm_stage('C61.9', 'T2', 'N0', 'M0', 'X', 'X'))
        self.assertEquals('I', tnm_stage('C61.9', 'T2a', 'N0', 'M0', 'X', 'X'))

    def test_prostate_cancer_IIA(self):
        self.assertEquals('IIA', tnm_stage('C61.9', 'T1a', 'N0', 'M0', '1', '7'))
        self.assertEquals('IIA', tnm_stage('C61.9', 'T1b', 'N0', 'M0', '1', '7'))
        self.assertEquals('IIA', tnm_stage('C61.9', 'T1c', 'N0', 'M0', '1', '7'))
        self.assertEquals('IIA', tnm_stage('C61.9', 'T1a', 'N0', 'M0', '15', '7'))
        self.assertEquals('IIA', tnm_stage('C61.9', 'T1b', 'N0', 'M0', '15', '7'))
        self.assertEquals('IIA', tnm_stage('C61.9', 'T1c', 'N0', 'M0', '15', '7'))

        self.assertEquals('IIA', tnm_stage('C61.9', 'T1a', 'N0', 'M0', '15', '6'))
        self.assertEquals('IIA', tnm_stage('C61.9', 'T1b', 'N0', 'M0', '15', '6'))
        self.assertEquals('IIA', tnm_stage('C61.9', 'T1c', 'N0', 'M0', '15', '6'))

        self.assertEquals('IIA', tnm_stage('C61.9', 'T2a', 'N0', 'M0', '15', '6'))

        self.assertEquals('IIA', tnm_stage('C61.9', 'T2a', 'N0', 'M0', '1', '7'))
        self.assertEquals('IIA', tnm_stage('C61.9', 'T2a', 'N0', 'M0', '15', '7'))

        self.assertEquals('IIA', tnm_stage('C61.9', 'T2b', 'N0', 'M0', '1', '6'))
        self.assertEquals('IIA', tnm_stage('C61.9', 'T2b', 'N0', 'M0', '15', '6'))
        self.assertEquals('IIA', tnm_stage('C61.9', 'T2b', 'N0', 'M0', '1', '7'))
        self.assertEquals('IIA', tnm_stage('C61.9', 'T2b', 'N0', 'M0', '15', '7'))

        self.assertEquals('IIA', tnm_stage('C61.9', 'T2b', 'N0', 'M0', 'X', 'X'))

    def test_prostate_cancer_IIB(self):
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '1', '6'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '15', '6'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '25', '6'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', 'X', '6'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '', '6'))

        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '1', '7'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '15', '7'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '25', '7'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', 'X', '7'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '', '7'))

        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '1', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '15', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '25', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', 'X', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '', '8'))

        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '1', 'X'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '15', 'X'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '25', 'X'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', 'X', 'X'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '', 'X'))

        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '1', ''))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '15', ''))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '25', ''))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', 'X', ''))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2c', 'N0', 'M0', '', ''))

        self.assertEquals('IIB', tnm_stage('C61.9', 'T1', 'N0', 'M0', '25', '6'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1a', 'N0', 'M0', '25', '6'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1b', 'N0', 'M0', '25', '6'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1c', 'N0', 'M0', '25', '6'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2', 'N0', 'M0', '25', '6'))

        self.assertEquals('IIB', tnm_stage('C61.9', 'T1', 'N0', 'M0', '25', '7'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1a', 'N0', 'M0', '25', '7'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1b', 'N0', 'M0', '25', '7'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1c', 'N0', 'M0', '25', '7'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2', 'N0', 'M0', '25', '7'))

        self.assertEquals('IIB', tnm_stage('C61.9', 'T1', 'N0', 'M0', '25', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1a', 'N0', 'M0', '25', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1b', 'N0', 'M0', '25', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1c', 'N0', 'M0', '25', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2', 'N0', 'M0', '25', '8'))

        self.assertEquals('IIB', tnm_stage('C61.9', 'T1', 'N0', 'M0', '25', 'X'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1a', 'N0', 'M0', '25', 'X'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1b', 'N0', 'M0', '25', 'X'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1c', 'N0', 'M0', '25', 'X'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2', 'N0', 'M0', '25', 'X'))

        self.assertEquals('IIB', tnm_stage('C61.9', 'T1', 'N0', 'M0', '25', ''))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1a', 'N0', 'M0', '25', ''))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1b', 'N0', 'M0', '25', ''))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1c', 'N0', 'M0', '25', ''))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2', 'N0', 'M0', '25', ''))

        self.assertEquals('IIB', tnm_stage('C61.9', 'T1', 'N0', 'M0', '1', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1', 'N0', 'M0', '15', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1', 'N0', 'M0', '25', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1', 'N0', 'M0', 'X', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1', 'N0', 'M0', '', '8'))

        self.assertEquals('IIB', tnm_stage('C61.9', 'T1a', 'N0', 'M0', '1', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1a', 'N0', 'M0', '15', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1a', 'N0', 'M0', '25', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1a', 'N0', 'M0', 'X', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1a', 'N0', 'M0', '', '8'))

        self.assertEquals('IIB', tnm_stage('C61.9', 'T1b', 'N0', 'M0', '1', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1b', 'N0', 'M0', '15', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1b', 'N0', 'M0', '25', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1b', 'N0', 'M0', 'X', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1b', 'N0', 'M0', '', '8'))

        self.assertEquals('IIB', tnm_stage('C61.9', 'T1c', 'N0', 'M0', '1', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1c', 'N0', 'M0', '15', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1c', 'N0', 'M0', '25', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1c', 'N0', 'M0', 'X', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T1c', 'N0', 'M0', '', '8'))

        self.assertEquals('IIB', tnm_stage('C61.9', 'T2', 'N0', 'M0', '1', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2', 'N0', 'M0', '15', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2', 'N0', 'M0', '25', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2', 'N0', 'M0', 'X', '8'))
        self.assertEquals('IIB', tnm_stage('C61.9', 'T2', 'N0', 'M0', '', '8'))

    def test_prostate_cancer_III(self):
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '1', '6'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '15', '6'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '25', '6'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', 'X', '6'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '', '6'))

        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '1', '6'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '15', '6'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '25', '6'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', 'X', '6'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '', '6'))

        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '1', '7'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '15', '7'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '25', '7'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', 'X', '7'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '', '7'))

        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '1', '7'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '15', '7'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '25', '7'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', 'X', '7'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '', '7'))

        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '1', '8'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '15', '8'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '25', '8'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', 'X', '8'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '', '8'))

        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '1', '8'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '15', '8'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '25', '8'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', 'X', '8'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '', '8'))

        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '1', 'X'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '15', 'X'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '25', 'X'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', 'X', 'X'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '', 'X'))

        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '1', 'X'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '15', 'X'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '25', 'X'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', 'X', 'X'))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '', 'X'))

        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '1', ''))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '15', ''))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '25', ''))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', 'X', ''))
        self.assertEquals('III', tnm_stage('C61.9', 'T3a', 'N0', 'M0', '', ''))

        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '1', ''))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '15', ''))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '25', ''))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', 'X', ''))
        self.assertEquals('III', tnm_stage('C61.9', 'T3b', 'N0', 'M0', '', ''))

    def test_prostate_cancer_IV(self):
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '25', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '25', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '25', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M0', '', ''))
        #segundo caso
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '25', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '25', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '25', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '25', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '25', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '25', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N1', 'M0', '', ''))
        #T1-2a
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N1', 'M0', '', ''))
        #T1-2
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N1', 'M0', '', ''))
        #T3a-b
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N1', 'M0', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N1', 'M0', '', ''))
        #terceira situacao  #T1a-c
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2b', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2c', 'N0', 'M1', '', ''))
        #T1-2a
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2a', 'N0', 'M1', '', ''))
        #T1-2
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1a', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1b', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1c', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T2', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T1', 'N0', 'M1', '', ''))
        #T3a-b
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3a', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T3b', 'N0', 'M1', '', ''))

        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '1', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '15', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '25', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', 'X', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '', '6'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '1', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '15', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '25', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', 'X', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '', '7'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '1', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '15', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '25','8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', 'X', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '', '8'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '1', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '15', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '25','X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', 'X', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '', 'X'))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '1', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '15', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '25',''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', 'X', ''))
        self.assertEquals('IV', tnm_stage('C61.9', 'T4', 'N0', 'M1', '', ''))